name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install
          npm install sass@latest --save-dev
          npm install @hello-pangea/dnd@latest --save
          npm install chart.js@latest --save
          npm install react-chartjs-2@latest --save
          npm install react-router-dom@latest --save

      - name: Build
        run: |
          export PATH=$PATH:$(npm bin)
          export CI=false
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages 